// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ28rhYfIOROqajGue2Hr04TKRt8sSSaU',
    appId: '1:67048107788:web:dff9ec329a1de9da1d6329',
    messagingSenderId: '67048107788',
    projectId: 'chatapp-847fe',
    authDomain: 'chatapp-847fe.firebaseapp.com',
    storageBucket: 'chatapp-847fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsqc7lzgz-XBJ2FVttZrtVZbGxnJl6W5k',
    appId: '1:67048107788:android:d43b15def3ba06341d6329',
    messagingSenderId: '67048107788',
    projectId: 'chatapp-847fe',
    storageBucket: 'chatapp-847fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRRTQFbdSS77fLpJrt2lM1bWjiWXFUAN8',
    appId: '1:67048107788:ios:0a4314c494eba8e51d6329',
    messagingSenderId: '67048107788',
    projectId: 'chatapp-847fe',
    storageBucket: 'chatapp-847fe.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRRTQFbdSS77fLpJrt2lM1bWjiWXFUAN8',
    appId: '1:67048107788:ios:0a4314c494eba8e51d6329',
    messagingSenderId: '67048107788',
    projectId: 'chatapp-847fe',
    storageBucket: 'chatapp-847fe.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ28rhYfIOROqajGue2Hr04TKRt8sSSaU',
    appId: '1:67048107788:web:b054330d350d65b01d6329',
    messagingSenderId: '67048107788',
    projectId: 'chatapp-847fe',
    authDomain: 'chatapp-847fe.firebaseapp.com',
    storageBucket: 'chatapp-847fe.appspot.com',
  );

}